### ISSUE TITLE
alignment code not working on pairs

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1516] opened 2020-01-22 13:47 UTC
```c++
#include <iostream>

#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/alignment/pairwise/all.hpp>

int main()
{
    using seqan3::operator""_dna4;

    std::pair sequences{"ACCA"_dna4,"ATTA"_dna4};

    seqan3::configuration alignment_config = seqan3::align_cfg::edit |
                                             seqan3::align_cfg::parallel{4};

    seqan3::align_pairwise(sequences, alignment_config);
}
```

Does not compile:

```
/seqan3/test/snippet/test_snippet.cpp: In function ‘int main()’:
/seqan3/test/snippet/test_snippet.cpp:15:55: error: no matching function for call to ‘align_pairwise(std::pair<std::vector<seqan3::dna4>, std::vector<seqan3::dna4> >&, seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::gap<seqan3::gap_scheme<signed char> >, seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::align_config_id, seqan3::detail::align_config_id::parallel> > >&)’
   15 |     seqan3::align_pairwise(sequences, alignment_config);
      |                                                       ^
In file included from /seqan3/include/seqan3/alignment/pairwise/all.hpp:15,
                 from /seqan3/test/snippet/test_snippet.cpp:4:
/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:139:16: note: candidate: ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = std::pair<std::vector<seqan3::dna4>, std::vector<seqan3::dna4> >&; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::gap<seqan3::gap_scheme<signed char> >, seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::align_config_id, seqan3::detail::align_config_id::parallel> > >]’
  139 | constexpr auto align_pairwise(sequence_t && seq, alignment_config_t const & config)
      |                ^~~~~~~~~~~~~~
/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:139:16: note:   constraints not satisfied
In file included from /seqan3/include/seqan3/alignment/pairwise/detail/type_traits.hpp:17,
                 from /seqan3/include/seqan3/alignment/pairwise/align_result_selector.hpp:23,
                 from /seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:24,
                 from /seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /seqan3/include/seqan3/alignment/pairwise/all.hpp:15,
                 from /seqan3/test/snippet/test_snippet.cpp:4:
/seqan3/include/seqan3/alignment/pairwise/detail/concept.hpp:109:16: note: within ‘template<class t> concept const bool seqan3::detail::align_pairwise_single_input<t> [with t = std::remove_reference<std::pair<std::vector<seqan3::dna4>, std::vector<seqan3::dna4> >&>::type]’
  109 | SEQAN3_CONCEPT align_pairwise_single_input =
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /seqan3/submodules/range-v3/include/range/v3/algorithm/copy.hpp:25,
                 from /seqan3/include/seqan3/alignment/scoring/scoring_scheme_base.hpp:16,
                 from /seqan3/include/seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp:16,
                 from /seqan3/include/seqan3/alignment/configuration/align_config_edit.hpp:19,
                 from /seqan3/include/seqan3/alignment/configuration/all.hpp:18,
                 from /seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:22,
                 from /seqan3/include/seqan3/alignment/pairwise/all.hpp:15,
                 from /seqan3/test/snippet/test_snippet.cpp:4:
/seqan3/submodules/range-v3/include/range/v3/range/concepts.hpp:287:22: note: within ‘template<class T> concept const bool ranges::viewable_range<T> [with T = std::vector<seqan3::dna4>]’
  287 |     CPP_concept_bool viewable_range =
      |                      ^~~~~~~~~~~~~~
/seqan3/submodules/range-v3/include/range/v3/range/concepts.hpp:91:22: note: within ‘template<class T> concept const bool ranges::forwarding_range_<T> [with T = std::vector<seqan3::dna4>]’
   91 |     CPP_concept_bool forwarding_range_ =
      |                      ^~~~~~~~~~~~~~~~~
```

I guess that the main problem here is that `std::pair::first` ( `std::vector<dna4>`) is not a viewable_range, because it is not of type  `std::vector<dna4> &`.

**Comment by rrahn** [comment] 2020-01-24 09:32
It is actually not a bug but a feature. So the documentation and the tutorials explicitly refer to this by saying one needs to use `std::tie` instead. Or the pair has to be converted to a single range before. The point is that we use internally a single range to wrap the pair. But that will copy the sequences and thus we cannot return an alignment that holds references to these temporaries. 

Alternatively, we need wrap each of the contained sequences inside of view::persist in order to make them persistent as long as there is a copy of them alive. Anyhow, this would be not a bug but a feature request 😏

**Comment by marehr** [comment] 2020-01-24 10:30
I can't follow you, the sequences are given as lvalue, they outlive the call, why should I call persist?

**Comment by rrahn** [comment] 2020-01-24 10:32
Inside of the function were we get the pair we call `views::single(pair)` and forward this to the alignment. This works only if the pair type stores viewable_ranges, which is in not the case in your example

**Comment by marehr** [comment] 2020-01-24 10:35
See https://docs.seqan.de/seqan/3-master-dev/group__pairwise__alignment.html#gab6ff083328a700c26c90fea870d63491

in that documentation there is an example:
```c++
std::pair p{"ACGTAGC", "AGTACGACG"};
auto rng = align_pairwise(p, config);
```

This example shows two things, first you thought that this should work and second we still have code snippets that re not tested :speak_no_evil:.

>  Inside of the function were we get the pair we call views::single(pair)  and forward this to the alignment. This works only if the pair type  stores viewable_ranges, which is not the case in your example

Yeah, in this case, because the tuple / pair is lvalue you can make the underlying sequences also lvalues. ANd this exactly the defect here. This should work.

**Comment by rrahn** [comment] 2020-01-24 10:40
If you would read the documentation carefully you could see that it explicitly describes that this would not compile.

To other point it would be sufficient to not use heap memory indeed:
```cpp
auto seq1_view = get<0>(sequence_pair) | views::type_reduce;
auto seq2_view = get<1>(sequence_pair) | views::type_reduce;
align_pairwise(std::views::single(std::pair{seq1_view, seq2_view}, ...);
```
So that could work. Still it is not a defect because it is a forbidden interface. It is a feature to allow it.

**Comment by marehr** [comment] 2020-01-24 10:42
> If you would read the documentation carefully you could see that it explicitly describes that this would not compile. :smirk:

Why is your first example an anti-example? As a keyword reader this is completely unexpected, there should be a fat headline that says, examples that **don't** work.

**Comment by rrahn** [comment] 2020-01-24 10:47
> Why is your first example an anti-example? As a keyword reader this is completely unexpected, there should be a fat headline that says, examples that don't work.

Well, improvements are welcome any time.

**Comment by marehr** [comment] 2020-01-24 10:55
Created an issue #1522 for the documentation

**Comment by smehringer** [comment] 2020-01-27 14:27
Can we close this issue then?

**Comment by rrahn** [comment] 2020-01-28 09:03
You mean converting it to a card? Otherwise, why would you close a valid feature request?

**Comment by smehringer** [comment] 2020-01-31 07:17
I thought I read that a pair **should** not compile so this is not a feature request?

**Comment by rrahn** [comment] 2020-06-10 08:58
Ok in summary we want this to work. To do so we need to wrap the given pair's elements using std::tie. Here is how it schould be handled internally:

```cpp
#include <ranges>
#include <string>
#include <vector>

int main()
{
    std::pair<std::string, std::string> p{"seq1", "seq2"};

    auto v = std::views::single(std::tie(p.first, p.second));
    using ref_t = std::ranges::range_reference_t<decltype(v)>;
    ref_t elem = *v.begin();

    return std::get<0>(elem).size() + std::get<1>(elem).size();
}
```  

### Acceptance criteria

- [ ] The above mentioned problem compiles and runs through

### Task

- [ ] Adapt the interface of align_pairwise with the necessary changes.
- [ ] Test that this new behavior works as expected.

**Closed** 2020-07-01 12:32 UTC
Labels: feature/proposal, ready for sprint
