### ISSUE TITLE
Compatibility with LTO

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan3#2013] opened 2020-08-07 11:02 UTC
Hello.

## Platform

  - SeqAn version: commit bf04354bab903dc7f8c12f3bb478c02cd5f2c553
  - Operating system: Fedora 33
  - Compiler: GNU-10.2.1

## Description

```
[  9%] Building CXX object alignment/matrix/detail/CMakeFiles/two_dimensional_matrix_test.dir/two_dimensional_matrix_test.cpp.o
cd /builddir/build/BUILD/seqan3/build/alignment/matrix/detail && /usr/bin/g++ -DSEQAN3_HAS_BZIP2=1 -DSEQAN3_HAS_ZLIB=1 -DSEQAN3_WITH_CEREAL=1 -DSEQAN3_WITH_LEMON=1 -I/usr/include/gtest -I/builddir/build/BUILD/seqan3/test/include -I/builddir/build/BUILD/seqan3/include -isystem /builddir/build/BUILD/seqan3/submodules/sdsl-lite/include -isystem /builddir/build/BUILD/seqan3/submodules/range-v3/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu++17 -fconcepts -lstdc++fs -DNDEBUG -pedantic -Wall -Wextra -Werror -pthread -o CMakeFiles/two_dimensional_matrix_test.dir/two_dimensional_matrix_test.cpp.o -c /builddir/build/BUILD/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp
*** WARNING *** there are active plugins, do not report this as a bug unless you can reproduce it without enabling any plugins.
Event                            | Plugins
PLUGIN_FINISH_UNIT               | annobin: Generate final annotations
PLUGIN_START_UNIT                | annobin: Generate global annotations
PLUGIN_ALL_PASSES_START          | annobin: Generate per-function annotations
PLUGIN_ALL_PASSES_END            | annobin: Register per-function end symbol
during IPA pass: pure-const
/builddir/build/BUILD/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp:420:1: internal compiler error: tree code 'typename_type' is not supported in LTO streams
  420 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

### How to repeat the problem

Compiling `seqan` with `gcc-10.2.1`, `cereal-1.3.0` `gtest-1.10.0` from system, bundled `sdsl-lite-3.0.0` and `range-v3-0.10.0`, on Fedora 33 (devel branch) with enabled LTO flags (`-flto=auto -ffat-lto-objects`). [LTO optimization](https://fedoraproject.org/wiki/LTOByDefault) is a feature recently introduced in Fedora 33+ by default.
I don't know if generated error can be considered a "bug" of Seqan but, since LTO will be required for all RPMs,  i ask to myself if was possible using those flags.
(Just for info, [i had to disable LTO flags](https://src.fedoraproject.org/rpms/seqan/c/7acd252c03d36bc6ccc7e63b84068e67eabd707d?branch=master) even in the Seqan1 RPM to override a linker fault. Was it a good choice?)

### Expected behaviour

??

### Actual behaviour

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/9216/48869216/build.log

Thank you.

**Comment by marehr** [comment] 2020-08-07 11:07
Thank you for reporting. This seems to be a compiler bug. I'll try to reduce this first and when see what we can do. But I think that this will have a pretty low priority.

Can you give me a docker image that can reproduce this internal compiler error?

**Comment by sagitter** [comment] 2020-08-07 12:28
I never used a docker but [this page](https://hub.docker.com/_/fedora?tab=tags) could be useful.

**Comment by marehr** [comment] 2020-08-07 12:29
Thank you, I could reproduce this error with my set-up, so a docker image wasn't needed.

**Comment by marehr** [comment] 2020-08-12 15:39
I could get it reduced to this:

```c++
template <typename scalar_t, unsigned length>
struct builtin_simd
{
  using type [[gnu::vector_size(sizeof(scalar_t) * length)]] = scalar_t;
};

struct simd_traits
{
  using scalar_type = int;

  template <typename new_scalar_type>
  using rebind = typename builtin_simd<new_scalar_type, 1>::type;
};

template <typename simd_t>
constexpr simd_t fill(typename simd_traits::scalar_type const scalar)
{
  return simd_t{scalar};
}

class Test
{
    using score_type = typename builtin_simd<int, 1>::type;
    score_type data[1]{fill<score_type>(8)};
};

struct TestFactoryBase
{
  virtual Test *CreateTest() = 0;
};

template <class TestClass>
struct TestFactoryImpl : public TestFactoryBase
{
  Test *CreateTest() override { return new TestClass; }
};

void MakeAndRegisterTestInfo(TestFactoryBase *factory);

int main() {
  MakeAndRegisterTestInfo(new TestFactoryImpl<Test>);
}
```

**Comment by marehr** [comment] 2020-08-12 16:00
I filed a bug report at gcc

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96591

**Comment by marehr** [comment] 2021-04-12 12:38
Closing as it is fixed by gcc, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96591.

**Closed by marehr** 2021-04-12 12:38 UTC
Labels: bug, external bug
