### ISSUE TITLE
[BUG] SAM does not allow user-defined tags in header

### ISSUE THREAD

**Issue by Irallia** [seqan/seqan3#2600] opened 2021-05-04 15:59 UTC
While testing iGenVar with real data (PacBio long reads from https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_10kb/alignment/) I ran into some errors:

```bash
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Illegal SAM header tag in @HG starting with: p
```
from header file:
```sam
@HD	VN:1.5	SO:coordinate	pb:3.0.1
```
and without the `pb:3.0.1`
```bash
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Illegal SAM header tag starting with: I
```
from a header line like
```sam
@RG	ID:35690b08	SM:HG002	PU:m54238_180628_014238	DS:READTYPE=CCS;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-400;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000	PL:PACBIO	PM:SEQUEL
```

## Platform

  - SeqAn version: 3.0.3
  - Operating system: Debian GNU/Linux 10
  - Compiler: gcc (Debian 8.3.0-6) 8.3.0

### How to repeat the problem

```bash
git clone https://github.com/seqan/iGenVar.git
git submodule update --recursive --init
cmake ../../Repos/iGenVar/ -Weverything
make -j 16

wget https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_10kb/alignment/HG002.Sequel.10kb.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam -nv

./build/iGenVar/bin/iGenVar -j HG002.Sequel.10kb.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam -o output.vcf
```

### Expected behaviour

iGenVar should run without errors

### Actual behaviour

`format_sam_base` throws `seqan3::format_error`

**Comment by eseiler** [comment] 2021-05-04 16:34
(If you want us to have a look at it): Can you provide some minimal seqan3 code that throws?

**Comment by Irallia** [comment] 2021-05-05 11:55
```cpp
#include <sstream>
#include <seqan3/io/sam_file/input.hpp>

auto sam_file_raw = R"(@HD	VN:1.5	SO:coordinate	pb:3.0.1
@SQ	SN:testchr	LN:249250621	M5:1b22b98cdeb4a9304cb5d48026a85128
@PG	PN:whatshap	ID:whatshap	VN:0.17	CL:whatshap haplotag --reference /pbi/dept/appslab/datasets/wr_references/hs37d5/this.fasta --output HG002.Sequel.10kb.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam ../../RTG.hg19.10x.trio-whatshap.vcf.gz /pbi/dept/appslab/projects/old/2018/wr_hg002_data_sharing/hg19_pbmm2/HG002.Q20.hs37d5.pbmm2.bam	m5:9d47df1972afe81d70dc4e4c59669352
test1	16	testchr	1	60	10M	=	1	0	GCGCGCGCGC	FFFFFFFFFF
)";

int main()
{
    seqan3::sam_file_input fin{std::istringstream{sam_file_raw}, seqan3::format_sam{}};
    auto rec = std::move(fin.front()); // rec now stores the data permanently
}
```

**Comment by eseiler** [comment] 2021-05-05 12:12
```cpp
int main()
{
    seqan3::sam_file_input fin{std::istringstream{sam_file_raw}, seqan3::format_sam{}};
    fin.header();
}
```
is enough to trigger the error

**Comment by Irallia** [comment] 2021-05-05 12:16
I think for the second error "Illegal SAM header tag starting with: I" it is just the order which is a problem

**Comment by eseiler** [comment] 2021-05-05 12:17
The problem is that there is `pb:3.0.1`. We throw in 
https://github.com/seqan/seqan3/blob/5f06c6f48284c5edaf25a7e587c98a58fbdd678f/include/seqan3/io/sam_file/detail/format_sam_base.hpp#L486
when there is something other than `SS`, `SO` or `GO`.

The specification states that additional tags in the header are allowed. In particular, lowercase tags are reserved for users.

So we would need to not throw and ... use a sam_tag_dictionary to store user specified tags? Or warn that we do not support them yet? Etc.

**Comment by Irallia** [comment] 2021-05-05 12:53
So far, we have no further use for this additional information at iGenVar. For us, a warning that it exists would therefore be more than sufficient.

Here is the explanation for the pb from PacBio:
```text
The PacBio BAM specification version described here is 4.0.0. PacBio BAM files adhering to this spec contain the tag pb:4.0.0 in the @HD header.
```
https://pacbiofileformats.readthedocs.io/en/10.0/BAM.html

**Comment by eseiler** [comment] 2021-05-20 06:57
Resolved by https://github.com/seqan/seqan3/pull/2605

**Closed by eseiler** 2021-05-20 06:57 UTC
Labels: bug
