### ISSUE TITLE
Arg parser misinterprets options with more than one dash

### ISSUE THREAD

**Issue by sarahet** [seqan/seqan3#1984] opened 2020-07-14 13:00 UTC
Hi all,

I found a problem when using the argument parser and using option names including more than one dash. For example:

```
    parser.add_option(options.gapOpen, '\0', "score-gap-open",
        "Additional cost for opening gap.", seqan3::option_spec::ADVANCED, seqan3::arithmetic_range_validator{-1000, 1000});
```
Setting this option when calling the program causes the following error:

```
Value cast failed for option --score-gap: Argument -open could not be casted to type signed 32 bit integer.
```
I observed this with any option that I tried giving a name with more than one dash.

I would appreciate any help :slightly_smiling_face:

**Comment by eseiler** [comment] 2020-07-14 14:45
Hey Sara,

can you verify that your SeqAn3 version is up to date?
I cannot reproduce the error - if you are up to date, there may be more to it than just this one option.

**Comment by rrahn** [comment] 2020-10-16 11:47
@sarahet could you check if this is still a problem and if yes please reopen the issue. I will close it for now since it seems fixed?

**Closed by rrahn** 2020-10-16 11:47 UTC
Labels: bug, response needed
